name: CI Build Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: 'windows-latest'

    steps:
      - uses: actions/checkout@v4

      - name: Build CI
        run: |
          make arm_sdk_install
          tools/windows/make/bin/make

      - name: Archive build
        uses: actions/upload-artifact@v3
        with:
          name: AM32-bootloader
          path: |
            obj/*.hex
          retention-days: 7
